version: "3"

services:
  postgres:
    container_name: database
    build:
      context: ./database
    ports:
      - "5432:5432"
    environment:
      environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
